domains:
- domain: nanzho.ng
- domain: www.nanzho.ng
name: nanzhong
region: ams3
static_sites:
- build_command: rm -r ./public; hugo --destination ./public
  environment_slug: hugo
  github:
    branch: master
    deploy_on_push: true
    repo: nanzhong/nanzho.ng
  name: www
  routes:
  - path: /
