baseURL = "https://nanzho.ng/"
languageCode = "en-ca"
title = "nanzho.ng"
theme = "nanzho.ng"
disqusShortname = "nanzhong"
googleAnalytics = "UA-88257352-2"

[menu]

  [[menu.main]]
    name = "nanzho.ng"
    url = "/"
    weight = 1
  
  [[menu.main]]
    name = "about"
    url = "/about"
    weight = 2
  
  [[menu.main]]
    name = "posts"
    url = "/posts"
    weight = 3

[params]

  [[params.social]]
    name = "github"
    link = "https://github.com/nanzhong"

  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/nanzhong"

  [[params.social]]
    name = "email"
    link = "me@nanzho.ng"

[markup]

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 2