#+TITLE: Dvorak - Day 1
#+DATE: <2014-03-10 01:03:08 -0400>
#+FILETAGS: :dvorak:

Other than sleep, the one thing that I do more than anything is typing on a keyboard. Growing up I've never thought much about typing, as a matter of fact I've never learned to properly touch-type. My left hand is pretty good, but my right hand pretty much consists of only typing with my index and middle fingers.

To me, speed or technique never felt important; typing was just a tool, a simple and basic skill. I'm not a speed typist, but my speed is more than enough to not hinder me in my daily tasks. While I was in university, I even felt like I typed faster than my peers, and as a result allowed me to pound out code more efficiently. 

This all changed about 4 months ago. One day my right wrist just didn't feel right, and typing for more than a few minutes at a time brought with it a really sour senstation. That's when alarm bells started going off in my head. I've heard about people developing repetitive strain injuries (RSI), but I just never thought it would happen to me. Thankfully it wasn't very serious yet, but one thing was certain: something needs to change.

I had heard about the DVORAK keyboard layout, and how it reduces finger/wrist movement reducing the risk of RSI, so around the middle of December of 2013, I decided to give it a try. It was by far the most annoying, depressing, and difficult experience I've had in a long while. It felt like I was trying to push honey through a tiny juice box straw; I knew what I wanted to type, I controlled my fingers, but I just couldn't do it properly. After a weekend of enduring this, I was typing at around 20 WPM. The next week came, and I tried to use DVORAK at work. Failed. One of the worst feeling I had was attempting to communicate with people over IM, knowing exactly what I want to say, but not being able to express myself in time for my responses to be meaningful.

A week went by; I would use QWERTY at work, DVORAK at home. I confused the heck out of myself, and decided to give up. By the end my QWERTY typing speed had dropped to around 50 WPM, and my DVORAK speed was just barely 30 WPM. I gave up.

By the end of the month, my right hand was in pain, and I was looking into expensive ergonomic keyboards like the [[http://www.kinesis-ergo.com/shop/advantage-pro-for-pc-mac/][Kinesis Advantage Pro]] and [[https://www.trulyergonomic.com/store/index.php][Truly Ergonomic Keyboard]].

Before pulling the trigger, I wanted to see if things would just "fix" themselves with some rest. I took a vacation for almost two weeks during I didn't touch a keyboard once. My pain was gone, and things were back to normal. In order to help reduce strain, I remapped keybindings, made sure to take frequent breaks, and even started going wrist and hand strengthening exercises. I thought things were fine, and they were for quite a few months.

Sadly, the pain is back, and this time I'm determined to make the switch. I guess it's ironic and cliche, but I really never realized how important being able to type is to me until I've gone through all this. I will be posting daily updates of my progress here along with the types of stuff I've been doing to help me convert in order to, hopefully, motivate myself and better understand what I'm doing right and wrong.

So, with today's fresh start, my typing speeds are sitting at:

QWERTY: *77* WPM
DVORAK: *24* WPM

Oh, I'm also looking to buy an ergonomic keyboard, currently debating between the [[https://www.trulyergonomic.com/store/index.php][TEK]] and [[http://ergodox.org/][Ergodox]], any opinions on which is more effective at reducing strain?
