#+TITLE: Dvorak - Day 2
#+DATE: <2014-03-11 01:45:40 -0400>
#+FILETAGS: :dvorak:

Monday marks the beginning of a new work-week. Since DVORAK at work isn't really an option at work, I had to think of another way to practice that was not going to kill my productivity.

So here's my plan for this week. For every hour of QWERTY, I will DVORAK for 10 minutes. This undoubtedly caused a ton of confusion, but I'm hoping that by doing this I won't cause my QWERTY speed to drop like last time.

So, is this really worth it? Am I even certain that switching a keyboard layout will even help with my wrist? The simple answer is no. Since I've never actually successfully switched over, I have no way of comparing, but I've heard [[http://xahlee.info/comp/dvorak_keyboard_layout.html][many]] [[http://matt.might.net/articles/preventing-and-managing-rsi/][people]] [[http://thepracticeofyourlife.com/2011/05/04/why-i-dont-recommend-dvorak/][say]] it's more "comfortable" and that it has helped with RSI. It seems that many people want to switch to DVORAK for the novelty, but for me the main motivation is comfort and not wanting to more permanently damage my right wrist and fingers.

QWERTY: *85* WPM
DVORAK: *30* WPM

I'm actually really surprised that my QWERTY speed improved, but I guess it could be related to my suddent switch to DVORAK yesterday that threw my speed off.
