name: Build
on:
  push:
    branches:
      - main

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          ssh-key: ${{ secrets.ORG_DEPLOY_KEY }}
          fetch-depth: 0

      - name: Restore org mtime
        run: |
          sudo apt-get -y install git-restore-mtime
          cd org
          git restore-mtime

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: nanzhong
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: nanzhong/nanzho.ng:latest,nanzhong/nanzho.ng:${{ github.sha }}
          cache-from: type=registry,ref=nanzhong/nanzho.ng:build-cache
          cache-to: type=registry,ref=nanzhong/nanzho.ng:build-cache,mode=max

      - name: Build and save
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: nanzhong/nanzho.ng:latest,nanzhong/nanzho.ng:${{ github.sha }}
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: /tmp/image.tar

  publish:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: public

      - name: Download image artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/image.tar

      - name: Setup git user
        run: |
          git config --global user.name "Nan Zhong"
          git config --global user.email "me@nanzho.ng"

      - name: Commit and push exported site to public branch
        run: |
          CID=$(docker create nanzhong/nanzho.ng)
          docker cp ${CID}:/var/www/html /tmp/html
          docker rm ${CID}

          git rm -rf --quiet *
          mv /tmp/html/* .
          git add .
          git status
          git commit -m "Publish site built from ${{ github.sha }}"
          git push origin public
