name: Build
on:
  push:
    branches:
      - main

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          ssh-key: ${{ secrets.ORG_DEPLOY_KEY }}
          fetch-depth: 0

      - name: Restore org mtime
        run: |
          sudo apt-get -y install git-restore-mtime
          cd org
          git restore-mtime

      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v10
        with:
          name: env
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true

      - name: Build site
        run: nix develop -c scripts/build.sh

      - name: Upload built site
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: output

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: public

      - name: Download build site
        uses: actions/download-artifact@v3
        with:
          name: site
          path: /tmp/output

      - name: Setup git user
        run: |
          git config --global user.name "Nan Zhong"
          git config --global user.email "me@nanzho.ng"

      - name: Commit and push exported site to public branch
        run: |
          git rm -rf --quiet *
          mv /tmp/output/* .
          git add .
          git status
          git commit -m "Publish site built from ${{ github.sha }}"
          git push origin public
