name: Deploy
on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Deploy
        run: doctl app create-deployment ${{ secrets.DO_APP_UUID }} --wait
